services:
#    gallery.example:
#        class: GalleryBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    gallery.pusher:
        class: GalleryBundle\GalleryPusher\GalleryPusher
        arguments: ["@service_container"]
