app_post:
    resource: "@AppBundle/Controller/PostController.php"
    type:     annotation

gallery:
    resource: "@GalleryBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
